
services:
  watchtower: #to watch service for new containers add label `com.centurylinklabs.watchtower.enable=true`
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.email=albertmirek@tetra-nova.space"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock

  client:
    image: ghcr.io/tetranova-labs/sober-october-client:prod
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.rule=Host(`tetra-nova.space`)"
      - "traefik.http.routers.client.entrypoints=websecure"
      - "traefik.http.routers.client.tls.certresolver=myresolver"
      - "com.centurylinklabs.watchtower.enable=true"
volumes:
  letsencrypt:
  #db-data:

#secrets:
#  db-password:
#    file: db/password.txt
